// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rzxjdzsdhwibexvdzvug.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ6eGpkenNkaHdpYmV4dmR6dnVnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0NzI0NDQsImV4cCI6MjA2MTA0ODQ0NH0.fyOGkpUaV5rzIJB31_CGmRUmMIb54jgpsvlfbaZhKnw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);